import { useEffect } from "react";

import AOS from "aos";

import "aos/dist/aos.css";

import { NewsletterSection } from "@/components/NewsletterSection";

const TermsCondition = () => {
  useEffect(() => {
    AOS.init({
      once: true,
    });
  }, []);

  return (
    <div className="w-full mx-auto">
      <div className="overflow-x-hidden w-full mx-auto pt-10 md:pt-16">
        <div className="mx-auto max-w-[1536px] px-4">
          <div className="relative mx-auto pb-14 text-center xl:pb-24">
            <h1
              className="text-4xl font-extrabold leading-tight text-purple-700 dark:text-white lg:text-[56px]"
              data-aos="zoom-in"
              data-aos-duration="1000"
            >
              Terms &amp; Conditions
            </h1>
          </div>

          <div className="space-y-12">
            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Terms and Conditions
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  This document is an electronic record in terms of the
                  Information Technology Act, 2000 and rules thereunder as
                  applicable and the amended provisions pertaining to electronic
                  records in various statutes as amended by the Information
                  Technology Act, 2000. This electronic record is generated by a
                  computer system and does not require any physical or digital
                  signatures.
                </p>

                <p>
                  This document is published in accordance with the provisions
                  of Rule 3(1) of the Information Technology (Intermediaries
                  Guidelines) Rules, 2011 that require publishing the rules and
                  regulations, privacy policy and Terms of Use for access or
                  usage of this website.
                </p>

                <p>
                  This website, including all materials present (excluding any
                  applicable third-party materials), is the property of Optivraflow
                  and is copyrighted and protected by worldwide copyright
                  laws and treaty provisions. You agree to comply with all
                  copyright laws worldwide in your use of this website and to
                  prevent any unauthorized copying of the materials.
                </p>

                <p>
                  By accessing this website we assume you accept these terms
                  &amp; conditions. Do not continue to use this website if you
                  do not agree to take all of the terms &amp; conditions stated
                  on this page.
                </p>

                <p>
                  The following terminology applies to these Terms and
                  Conditions, Privacy Statement and Disclaimer Notice and all
                  Agreements: "Client", "You" and "Your" refers to you, the
                  person or entity accessing this website and our services,
                  compliant to the Company&apos;s terms and conditions. "The
                  Company", "Ourselves", "We", "Our" and "Us", refers to Optivraflow,
                  a software development company. "Party", "Parties", or
                  "Us", refers to both the Client and ourselves.
                </p>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Cookies
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  We employ the use of cookies and similar tracking
                  technologies. By accessing this website, you agree to use
                  cookies in agreement with Optivraflow&apos;s Privacy Policy.
                </p>

                <p>
                  Cookies are used by our website to enhance user experience,
                  analyze website traffic, and enable the functionality of
                  certain areas. We use both session cookies (which expire when
                  you close your browser) and persistent cookies (which remain
                  on your device until deleted). You can control cookie
                  preferences through your browser settings.
                </p>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                License
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  Unless otherwise stated, Optivraflow and/or its licensors own
                  the intellectual property rights for all material on this
                  website, including but not limited to software code, designs,
                  graphics, text, logos, and documentation. All intellectual
                  property rights are reserved. You may access this website for
                  your own personal or business use subject to restrictions set
                  in these terms and conditions.
                </p>

                <p> You must not:</p>

                <ul className="list-disc ps-7">
                  <li>Republish material from this website</li>

                  <li>Sell, rent or sub-license material from this website</li>

                  <li>
                    Reproduce, duplicate or copy material from this website
                  </li>

                  <li>Redistribute content from this website</li>
                </ul>

                <p>
                  Parts of this website may offer opportunities for users to
                  post comments, feedback, or exchange information. Any such
                  content does not reflect the views and opinions of Optivraflow,
                  its employees, agents, and/or affiliates. User-generated
                  content reflects solely the views and opinions of the person
                  who posts such content.
                </p>

                <div className="mt-7">
                  <h3 className="font-semibold text-purple-700 dark:text-white">
                    You warrant and represent that:
                  </h3>

                  <ul className="mt-4 list-disc ps-7">
                    <li>
                      You are entitled to post the comments on our website and
                      have all necessary licenses and consents to do so.
                    </li>

                    <li>
                      The comments do not invade any intellectual property
                      right, including without limitation copyright, patent or
                      trademark of any third party.
                    </li>
                  </ul>
                </div>

                <div className="mt-7">
                  <h3 className="font-semibold text-purple-700 dark:text-white">
                    Third Party Content
                  </h3>

                  <ul className="mt-4 list-disc ps-7">
                    <li>
                      The comments do not contain any defamatory, libelous,
                      offensive, indecent or otherwise unlawful material which
                      is an invasion of privacy.
                    </li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Software Services and Licensing
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  When you engage Optivraflow for software development services,
                  the following terms apply:
                </p>

                <ul className="list-disc ps-7">
                  <li>
                    Custom software developed for you will be subject to a
                    separate service agreement that specifies ownership rights,
                    licensing terms, and deliverables.
                  </li>

                  <li>
                    Unless otherwise agreed in writing, you retain ownership of
                    custom software developed specifically for your business
                    needs.
                  </li>

                  <li>
                    Optivraflow retains rights to any pre-existing code,
                    frameworks, libraries, or tools used in the development
                    process.
                  </li>

                  <li>
                    Source code and documentation will be delivered as specified
                    in the service agreement, subject to full payment of
                    outstanding invoices.
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Service Availability and Support
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  While we strive to ensure our website and services are
                  available 24/7, we do not guarantee uninterrupted access. We
                  may perform maintenance, updates, or experience technical
                  issues that temporarily affect availability.
                </p>

                <p>
                  Support services, including bug fixes, updates, and technical
                  assistance, are provided according to the terms specified in
                  your service agreement. Standard support hours and response
                  times will be outlined in your contract.
                </p>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Limitation of Liability
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  To the maximum extent permitted by law, Optivraflow shall not be
                  liable for any indirect, incidental, special, consequential,
                  or punitive damages, including but not limited to loss of
                  profits, data, or business opportunities, arising from the use
                  of our website or services.
                </p>

                <p>
                  Our total liability for any claims arising from these terms or
                  our services shall not exceed the amount paid by you to Optivraflow
                  in the twelve (12) months preceding the claim.
                </p>
              </div>
            </section>

            <section>
              <h2 className="pb-7 text-[26px] font-bold leading-tight text-purple-700 dark:text-white">
                Hyperlinking to our Content
              </h2>

              <div className="space-y-5 leading-[30px]">
                <p>
                  The following organizations may link to our website without
                  prior written approval:
                </p>

                <ul className="list-disc ps-7">
                  <li>Government agencies</li>

                  <li>Search engines</li>

                  <li>News organizations</li>

                  <li>
                    Online directory distributors may link to our website in the
                    same manner as they hyperlink to the websites of other
                    listed businesses.
                  </li>
                </ul>
              </div>
            </section>
          </div>

          <div className="pt-16 lg:pt-24">
            <NewsletterSection />
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsCondition;
